import type { BossAttack, ArenaTrap, EncounterConfig } from '../types/game';

export const BOSS_ATTACKS: BossAttack[] = [
  {
    id: 'flame_cleave',
    name: 'Infernal Cleave',
    phaseRequired: 1,
    manaCost: 15,
    cooldown: 4,
    currentCooldown: 0,
    windupTime: 1.2,
    damage: 35,
    description: 'A wide 120-degree frontal sword arc. Punishes greedy melee speedrunners.',
    rangeType: 'cone',
    radius: 140,
    icon: 'Sword',
  },
  {
    id: 'inferno_slam',
    name: 'Molten Ground Slam',
    phaseRequired: 1,
    manaCost: 25,
    cooldown: 6,
    currentCooldown: 0,
    windupTime: 1.8,
    damage: 60,
    description: 'Massive circular seismic blast around the boss. Leaves burning embers.',
    rangeType: 'circle',
    radius: 170,
    icon: 'Flame',
  },
  {
    id: 'shockwave_jump',
    name: 'Raid-Wide Shockwave',
    phaseRequired: 1,
    manaCost: 35,
    cooldown: 9,
    currentCooldown: 0,
    windupTime: 2.2,
    damage: 40,
    description: 'Arena-wide expanding ring wave. Forces runners to roll or get staggered.',
    rangeType: 'full_arena',
    radius: 400,
    icon: 'Radio',
  },
  {
    id: 'magma_pillar',
    name: 'Erupting Lava Pillar',
    phaseRequired: 1,
    manaCost: 20,
    cooldown: 5,
    currentCooldown: 0,
    windupTime: 1.5,
    damage: 50,
    description: 'Targets the furthest ranged speedrunner with an erupting geyser.',
    rangeType: 'circle',
    radius: 90,
    icon: 'Zap',
  },
  {
    id: 'summon_imps',
    name: 'Dev-Spawn Adds (x3)',
    phaseRequired: 1,
    manaCost: 30,
    cooldown: 12,
    currentCooldown: 0,
    windupTime: 1.0,
    damage: 20,
    description: 'Spawns 3 fiery imps to harass the Mage and interrupt potion buffs.',
    rangeType: 'circle',
    radius: 100,
    icon: 'Users',
  },
  // Phase 2 Exclusive Attacks
  {
    id: 'apocalypse_laser',
    name: 'Apocalypse Sweeping Beam',
    phaseRequired: 2,
    manaCost: 40,
    cooldown: 8,
    currentCooldown: 0,
    windupTime: 1.8,
    damage: 90,
    description: 'Rotational death ray that sweeps across the entire arena floor.',
    rangeType: 'line',
    radius: 380,
    icon: 'Crosshair',
  },
  {
    id: 'meteor_shower',
    name: 'Cataclysm Meteor Rain',
    phaseRequired: 2,
    manaCost: 45,
    cooldown: 10,
    currentCooldown: 0,
    windupTime: 2.0,
    damage: 75,
    description: 'Barrage of 5 molten meteors targeted directly at all runner positions.',
    rangeType: 'circle',
    radius: 120,
    icon: 'Sparkles',
  },
  {
    id: 'supernova',
    name: 'Supernova Enrage Nova',
    phaseRequired: 2,
    manaCost: 60,
    cooldown: 15,
    currentCooldown: 0,
    windupTime: 2.8,
    damage: 130,
    description: 'Climactic boss ultimate! Huge cinematic explosion to wipe the raid.',
    rangeType: 'full_arena',
    radius: 400,
    icon: 'Sun',
  },
];

export const ARENA_TRAPS: ArenaTrap[] = [
  {
    id: 'trap_lava',
    name: 'Floor Collapse (Lava Tile)',
    cost: 20,
    cooldown: 4,
    currentCooldown: 0,
    type: 'lava_pool',
    description: 'Spawns a boiling pool of magma. Deals DOT and cuts off speedrunner shortcuts.',
    icon: 'Flame',
  },
  {
    id: 'trap_wall',
    name: 'Hotfixed Collision Barrier',
    cost: 25,
    cooldown: 6,
    currentCooldown: 0,
    type: 'invisible_wall',
    description: 'Deploys an impassable invisible collision box to block corner clips.',
    icon: 'Shield',
  },
  {
    id: 'trap_spikes',
    name: 'Anti-Roll Caltrops',
    cost: 15,
    cooldown: 5,
    currentCooldown: 0,
    type: 'anti_roll_spikes',
    description: 'Ground spikes that nullify dodge roll i-frames and inflict bleed.',
    icon: 'AlertTriangle',
  },
];

export const ENCOUNTERS: EncounterConfig[] = [
  {
    id: 'encounter_1',
    title: 'Act 1: The Any% Qualifier Raid',
    bossName: 'Lord Ignis',
    bossTitle: 'The Sundered Pyrelord',
    difficulty: 'Casual Any%',
    bossMaxHp: 3000,
    phase2HpThreshold: 0.50, // 50%
    glitchAggression: 1.5,
    targetFightTime: 120,
    description: 'An amateur speedrun crew trying to break the 2-minute mark with potion stacking and basic corner clips. Make sure Phase 2 triggers in full glory!',
    runners: [
      { name: 'xX_GamerGlitch_Xx', className: 'rogue', hp: 320, dps: 35, chatFrequency: 6 },
      { name: 'MinMaxGod', className: 'mage', hp: 240, dps: 55, chatFrequency: 8 },
      { name: 'ParryGod69', className: 'tank', hp: 480, dps: 20, chatFrequency: 7 },
      { name: 'TwitchChat_Andy', className: 'bard', hp: 280, dps: 25, chatFrequency: 5 },
    ],
  },
  {
    id: 'encounter_2',
    title: 'Act 2: SGDQ Mainstage Marathon',
    bossName: 'Giga-Gargoyle',
    bossTitle: 'Warden of the Out-of-Bounds Abyss',
    difficulty: 'WR Pace',
    bossMaxHp: 4200,
    phase2HpThreshold: 0.50,
    glitchAggression: 2.8,
    targetFightTime: 140,
    description: 'They have 200,000 live viewers on Twitch. If they skip Phase 2 on the marathon stream, your boss engineering career is over!',
    runners: [
      { name: 'FramePerfect_Dan', className: 'rogue', hp: 380, dps: 45, chatFrequency: 5 },
      { name: 'PotStacker_420', className: 'mage', hp: 290, dps: 70, chatFrequency: 6 },
      { name: 'ShieldBuster', className: 'tank', hp: 550, dps: 28, chatFrequency: 5 },
      { name: 'SubTwo_OrRiot', className: 'bard', hp: 340, dps: 32, chatFrequency: 4 },
    ],
  },
  {
    id: 'encounter_3',
    title: 'Act 3: TAS AI Apocalypse',
    bossName: 'Omni-Lich 3000',
    bossTitle: 'Architect of Forbidden Frame Inversions',
    difficulty: 'TAS Insanity',
    bossMaxHp: 5500,
    phase2HpThreshold: 0.50,
    glitchAggression: 4.5,
    targetFightTime: 160,
    description: 'Tool-Assisted input bots executing sub-pixel geometry clip loops and multi-potion damage overflow. You will need maximum APM hotpatching!',
    runners: [
      { name: 'TAS_Bot_01', className: 'rogue', hp: 440, dps: 60, chatFrequency: 4 },
      { name: 'BufferOverflow_VIP', className: 'mage', hp: 340, dps: 90, chatFrequency: 4 },
      { name: 'InvulnFrame_Max', className: 'tank', hp: 620, dps: 40, chatFrequency: 4 },
      { name: 'Desync_Overlord', className: 'bard', hp: 390, dps: 45, chatFrequency: 4 },
    ],
  },
];
